version: "3"
services:
  node:
    image: node:latest
    user: node
    working_dir: /home/node/app
    expose:
      - 3000
    entrypoint: /bin/bash
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
